version: '3'
#Docker Networks
#Volumes
volumes:
  mysql:
    driver: local
  redis:
    driver: local

services:
  app:
    #build:
    #  context: ./docker
    image: sailorpapay/pack:php
    restart: unless-stopped
    tty: true
    volumes:
      - /tmp/github/:/var/www:cached
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
  #Nginx Service
  nginxpack:
  #  build:
  #    context: ./docker/nginx
    restart: unless-stopped
    image: sailorpapay/pack:nginx
    tty: true
    ports:
      - "8088:80"
    volumes:
      - /tmp/github/:/var/www:cached
      - ./docker/nginx/local/conf.d/:/etc/nginx/conf.d/


  #MySQL Service
  mysql:
    image: mysql:5.7.22
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    tty: true
    ports:
      - "33076:3306"
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
      MYSQL_USER: owner
      MYSQL_PASSWORD: root
    volumes:
#      - ./docker/mysql/gametrivia.sql:/docker-entrypoint-initdb.d/gametrivia.sql
#      - mysql:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf

  redis:
    image: redis:latest
    volumes:
      - redis:/data
    ports:
      - "63789:6379"
